runtime: python39

env_variables:
  SQLALCHEMY_DATABASE_URI: sqlite:///db.sqlite

handlers:
  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
