runtime: python39

instance_class: F2

env_variables:
  MYSQL_HOST: '<mysql_host>'
  MYSQL_USER: '<mysql_user>'
  MYSQL_PASSWORD: '<mysql_password>'
  MYSQL_DB: '<mysql_database>'
  SECRET_KEY: 'bangkit'

handlers:
- url: /api/.*
  script: auto
