runtime: python39
entrypoint: gunicorn -b :$port main:app

env_variables:
  MYSQL_HOST: '%'
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: ''
  MYSQL_DB: 'userdb'
  SECRET_KEY: 'bangkit'

handlers:
- url: /api/.*
  script: auto

- url: /.*
  static_files: static/index.html
  upload: static/index.html

- url: /static
  static_dir: static
